/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElImage: typeof import('element-plus/es')['ElImage']
    VirtualEstimatedList: typeof import('./src/components/VirtualEstimatedList.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList.vue')['default']
    WaterFall: typeof import('./src/components/WaterFall.vue')['default']
    WaterFallVirtual: typeof import('./src/components/WaterFallVirtual.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
